### DISCUSSION TITLE
Training always failing at exactly 75%

### DISCUSSION THREAD

**Discussion by stnokott** [dscripka/openWakeWord#62] [Q&A]
Hey there,

I'm using [notebooks/automatic_model_training.ipynb](https://github.com/dscripka/openWakeWord/blob/2d663e8c680320360738813ecd4a71faad3213e2/notebooks/automatic_model_training.ipynb) and can't get past the very last step.

I'm running `%run openwakeword/openwakeword/train.py --training_config my_model.yaml --train_model` in Jupyter running as a Docker container.

The command always **fails at exactly 75%**, killing the Jupyter kernel. So no error message, nothing, it just dies.
Running with `python openwakeword/openwakeword/train.py ..` inside the container has the same effect.

So usually I would blame this on my tiny 16GB RAM and 4GB of VRAM (RTX 2060) and some sort of out-of-memory issue, but considering that it reliably fails at **exactly 75%, regardless of sample size or steps** (tried as low as 1000 samples with 100 steps), there's probably something else the issue.

Is something special happening during training when at 75%?

Output of above-mentioned Jupyter command:
```
%run openwakeword/openwakeword/train.py --training_config my_model.yaml --train_model
```
```
/usr/local/anaconda3/lib/python3.10/site-packages/torchvision/io/image.py:13: UserWarning: Failed to load image Python extension: '/usr/local/anaconda3/lib/python3.10/site-packages/torchvision/image.so: undefined symbol: _ZN3c104cuda20CUDACachingAllocator9allocatorE'If you don't plan on using image functionality from `torchvision.io`, you can ignore this warning. Otherwise, there might be something wrong with your environment. Did you have `libjpeg` or `libpng` installed before building `torchvision` from source?
  warn(
torchvision is not available - cannot save figures
INFO:root:##################################################
Starting training sequence 1...
##################################################
Training:  75%|███████▌  | 75/100 [00:05<00:00, 47.07it/s]
```

Config for reference (from the run with the lowest steps/samples):
```yaml
augmentation_batch_size: 16
augmentation_rounds: 1
background_paths:
- ./audioset_16k
- ./fma
background_paths_duplication_rate:
- 1
batch_n_per_class:
  ACAV100M_sample: 1024
  adversarial_negative: 50
  positive: 50
custom_negative_phrases: []
false_positive_validation_data_path: validation_set_features.npy
feature_data_files:
  ACAV100M_sample: openwakeword_features_ACAV100M_2000_hrs_16bit.npy
layer_size: 32
max_negative_weight: 1500
model_name: ok_Homie
model_type: dnn
n_samples: 1000
n_samples_val: 500
output_dir: ./my_custom_model
piper_sample_generator_path: ./piper-sample-generator
rir_paths:
- ./mit_rirs
steps: 100
target_accuracy: 0.6
target_false_positives_per_hour: 0.2
target_phrase:
- ok Homie
target_recall: 0.25
tts_batch_size: 50
```

**Comment by stnokott** [comment]
Also probably worth mentioning:

Neither RAM nor VRAM are 100% used when the training fails. The usage is high, but no higher than 85% at any time.

**Comment by dscripka** [comment]
This is indeed an interesting failure, I haven't seen an issue like this before. A few clarifying questions:

1) You said you have 4GB of VRAM on an RTX 2060? I didn't realize that there was a 4GB version. Do you have other processes using some GPU RAM at the same time you are training the model?

2) The failure at the 75% is somewhat telling as that is when the training process starts doing checks on the validation data. This could be pushing your GPU RAM just over the limit and causes the kernel to crash.

One way to test this theory is to significantly reduce the batch size (`batch_n_per_class`) for the ACAV100M data, and see if you still have failures in that case. Finally, as a last resort you could try training with just CPU. This will still be reasonably fast (the models are very small and train quickly even on CPU), and since it can use your 16GB system ram (plus caching from disk) you shouldn't have any memory issues.

**Reply by stnokott** [reply]
Ah wow, I'm a moron, you are right, 8GB of VRAM of course, my apologies.

I'll try reducing the batch size, thanks!

**Reply by stnokott** [reply]
Unfortunately, the same thing happens with as low as 16 batch size for ACAV100M.

Config:
```yaml
augmentation_batch_size: 16
augmentation_rounds: 1
background_paths:
- ./audioset_16k
- ./fma
background_paths_duplication_rate:
- 1
batch_n_per_class:
  ACAV100M_sample: 16
  adversarial_negative: 50
  positive: 50
custom_negative_phrases: []
false_positive_validation_data_path: validation_set_features.npy
feature_data_files:
  ACAV100M_sample: openwakeword_features_ACAV100M_2000_hrs_16bit.npy
layer_size: 32
max_negative_weight: 1500
model_name: ok_Homie
model_type: dnn
n_samples: 1000
n_samples_val: 500
output_dir: ./my_custom_model
piper_sample_generator_path: ./piper-sample-generator
rir_paths:
- ./mit_rirs
steps: 100
target_accuracy: 0.6
target_false_positives_per_hour: 0.2
target_phrase:
- ok Homie
target_recall: 0.25
tts_batch_size: 50
```
