### DISCUSSION TITLE
Where to put new wake word files

### DISCUSSION THREAD

**Discussion by jmorris644** [dscripka/openWakeWord#90] [General]
Sorry for such a basic question, but where do I put the .tflite and .onnx files after they are created? I put them in the custom dir but it seems as if they are net being seen. At lease they are not being offered as choices in HA.

**Comment by dscripka** [comment]
Hey @jmorris644, are you trying to use your openWakeWord models with Home Assistant? If so, do the instructions [here](https://github.com/home-assistant/addons/blob/master/openwakeword/DOCS.md#custom-wake-word-models) not work?

If so, it's likely the problem is with Home Assistant configuration or the Home Assistant openWakeWord add-on.

**Reply by jmorris644** [reply]
I installed openwakeword on a different server than HA. So I am not using the Addon. I did the same with piper and whisper. 

I use the following docker-compose file to start up openwakeword
```
  openwakeword:
    container_name: openwakeword
    image: rhasspy/wyoming-openwakeword
    volumes:
      - /home/joe/whisper/custom/models:/custom
    restart: unless-stopped
    ports:
      - 10400:10400
```
I tried putting the files in the custom dir, but that did not work.
