### ISSUE TITLE
Poor Performance with automatic_model_training.ipynb

### ISSUE THREAD

**Issue by lea-xtend-ai** [dscripka/openWakeWord#110]
Hi,

I tried to use [automatic_model_training.ipynb](https://github.com/dscripka/openWakeWord/blob/main/notebooks/automatic_model_training.ipynb) but encountered significant issues, resulting in a model that does not work effectively at all.

**Configuration YAML Used**
```yaml
{'augmentation_batch_size': 16,
 'augmentation_rounds': 1,
 'background_paths': ['./audioset_16k', './fma'],
 'background_paths_duplication_rate': [1],
 'batch_n_per_class': {'ACAV100M_sample': 1024,
  'adversarial_negative': 50,
  'positive': 50},
 'custom_negative_phrases': [],
 'false_positive_validation_data_path': 'validation_set_features.npy',
 'feature_data_files': {'ACAV100M_sample': 'openwakeword_features_ACAV100M_2000_hrs_16bit.npy'},
 'layer_size': 32,
 'max_negative_weight': 1500,
 'model_name': 'alice',
 'model_type': 'dnn',
 'n_samples': 10000,
 'n_samples_val': 2000,
 'output_dir': './my_custom_model',
 'piper_sample_generator_path': './piper-sample-generator',
 'rir_paths': ['./mit_rirs'],
 'steps': 50000,
 'target_accuracy': 0.7,
 'target_false_positives_per_hour': 0.2,
 'target_phrase': ['alice'],
 'target_recall': 0.5,
 'tts_batch_size': 50}
```

**Output Results:**
```
Final Model Accuracy: 0.6267499923706055
Final Model Recall: 0.25699999928474426
Final Model False Positives per Hour: 1.0619468688964844
```
I tested using the detect_from_microphone script.

**On the other hand**, I successfully trained using  [training_models.ipynb](https://github.com/dscripka/openWakeWord/blob/main/notebooks/training_models.ipynb) with [synthetic_speech_dataset_generation](https://github.com/dscripka/synthetic_speech_dataset_generation)  for generating 10,000 samples (5000 for each model), and the results were fine without downloading the full negative data.

**Questions**
1. What might be causing the disparity in performance between the two notebooks?
2. For `training_models.ipynb`:
   2.1. Do I need to download the entire negative dataset, and if so, what is the total size in GB?
   2.2. Is generating 50,000 positive samples for each model necessary?
3. Any additional advice or constructive feedback would be greatly appreciated.

Thank you!
